# Site settings
title: Taylor's Portfolio
email: coomertaylor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://taylorcoomer.net" # the base hostname & protocol for your site

# User setting
owner: Taylor Coomer
email: coomertaylor@gmail.com
#facebook_username: 
#twitter_username: example
github_username: TrivialPants
#address:
 # - line: 3481 Melrose Hill St
 # - line: "Los Angeles, CA 90029"
  # Feel free to add more lines here 
telephone: (731) 487-2220
copyright: #Your Site

# API settings
google_api_key: #AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ

# Build settings
markdown: kramdown
